### ISSUE TITLE
problem when wifi password is only numbers

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#1]
I have found the issue, and fixed it, in order to do edit init_wifi.lua and replace:

`cfg.pwd = p:len()>=8 and p or nil`

with:

`cfg.pwd = tostring(p):len()>=8 and p or nil`

**Comment by bondrogeen** [comment]
( cfg.pwd = p:len()>=8 and p or nil ) == ( cfg.pwd = tostring(p):len()>=8 and p or nil )

What exactly does not work?
This is the same code, only a different approach.

**Comment by nedoskiv** [comment]
> lua: init_wifi.lua:4: attempt to index a number value
> stack traceback:
> 	init_wifi.lua:4: in function <init_wifi.lua:1>
> 	init.lua:11: in main chunk
> 	[C]: ?

it is same code, with a little fix, guess it is json issue to make variable number when it contains only numbers

**Comment by bondrogeen** [comment]
I did not think about it, I will correct it.
Thank you.
