### ISSUE TITLE
web_get.lua

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#10]
There is nothing wrong that I have seen with it, just trying to understand how it works. Do it download single file from external web server, or download multiple files. Also I take look at the code and cannot understand what "cb" do, is it a variable, function or array, where it was defined.

**Comment by bondrogeen** [comment]
This test, this script implements the ability to download data or files from the network, to update the scripts.

cb is a callback function
``` lua
t = {}
t.host = "git.codedevice.ru"
t.port = 80
t.path = "/files/TDA7313/"
t.file = "index.php"
--t.init = "upload"

- with callback
 
dofile ("web_get.lua") (t, function (res)
  print (res) - response from the server
end)

-- or without callback

dofile ("web_get.lua") (t) 

-- the response from the server will be stored in the file temp_get.txt

```

**Comment by nedoskiv** [comment]
I got confused with all those callback function and lost track of how that script work. But it work without problem. Thank you
