### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#4]
While server sending a file and you press browser refresh button, before it finish sending it. Free heap decreases with almost same size of file where it is interrupted on. If you hit several times refresh button E:M errors start to show in console or  device restarts.

**Comment by bondrogeen** [comment]
So it should be, you can not make frequent requests to the server, because each new request takes up the memory. Between requests, there should be a delay until the memory is freed.

**Comment by nedoskiv** [comment]
it is not that way.  i have located the problem and found a solution,problem is probably lua VM bug. Let me explain - in your web.lua file, you set the server and create a local scope coroutine which normally is closed when file is served, but if server is interrupted and client close connection, routine that detect finishing sending the file is never executed. Tcp connection is closed, but somehow local scope coroutine remain in memory and cause memory leak. So I moved coroutine in global scope, that usually fix memory leak, but prevent server from loading multi-fles, thank to lua agility  I assign coroutines to array bound with served files and now it can handle unlimited quick press of refresh buttons. Here is fix that I use:
-------- file begin

srv = net.createServer(net.TCP,10)
cr={}
srv:listen(80,function(conn)
 local cn
 conn:on("receive", function(conn,payload)
-- while true
--	do
--		if cr == nil then print ("cr nil") break end
--		if coroutine.status(cr) ~= "dead"
--				then
--					print ("cr res")
--					coroutine.resume(cr)
--				else
--					print ("cr destroy")
--					cr = nil
--					collectgarbage()
--					conn:close()
--		end
--	end
 	
	local req = dofile("web_request.lua")(payload)
	cn=req.uri.file
	cr[cn] = nil
	collectgarbage()
	if req
		then
			cr[cn] = coroutine.create(dofile("web_file.lua"))
--			print ("[ DEBUG ] cr create 1")
	end

	if (req and req.method == "GET")
		then
			if coroutine.status(cr[cn]) ~= "dead"
				then
--					print ("[ DEBUG ] CR call 1 ")
--					print (req.uri.file, req.uri.args,req.cookie)
					local b,res = coroutine.resume(cr[cn], conn, req.uri.file, req.uri.args,req.cookie)
				end
		elseif req and req.method == "POST"
			then
--				print ("[ DEBUG ] web_file call 1 ")
--				print (req.uri.file,req.getRequestData(payload),req.cookie)
				dofile("web_file.lua")(conn, req.uri.file,req.getRequestData(payload),req.cookie)
	end
	print(node.heap())
end)

 conn:on("sent", function(conn)
 if cr[cn]
	then
		local crStatus = coroutine.status(cr[cn])
		if crStatus == "suspended"
			then
--				print ("[ DEBUG ] CR call 2 ")
				local status, err = coroutine.resume(cr[cn])
				if not status
					then
						conn:close()
--						print ("[ DEBUG ] conn close. cr remove 1 ")
						cr[cn] = nil
						collectgarbage()
				end
			elseif crStatus == "dead" 
				then
					conn:close()
--					print ("[ DEBUG ] conn close. cr remove 2 ")
					cr[cn] = nil
					collectgarbage()
		end
 end
end)
end)
srv_init=true

----------- file end
you are a much more  optimized programmer than me and gonna strip a few lines for sure :)

**Comment by bondrogeen** [comment]
I'll check it well, but I think it will not be a universal solution anyway.

**Comment by bondrogeen** [comment]
Yes, your edits fix the memory leak.
Thank you.

**Comment by nedoskiv** [comment]
You are welcome. However there still can be a memory leak, if file is requested and connection is closed before it was served. Coroutine will remain in memory if file with same name is not requested again. Consider adding a tmr in web.lua. To delete all coroutines 10 after server become inactive. This will make it perfect.

**Comment by bondrogeen** [comment]
![image](https://user-images.githubusercontent.com/17860636/36937603-05448146-1f27-11e8-9f62-5bb35296d845.png)

https://github.com/bondrogeen/web-server.RC522

**Comment by nedoskiv** [comment]
Nice looking, I plan mine to have individual file for every RFID tag, containing name, usage counter and some other data if necessary.. Device gonna be able to give statistics for past period for each tag.  Guess can be used as cheap access/counting control for elevators, or  building entrances. Gonna ask for some javascript help when finish web interface.
--------------------------------------------
On Sat, 3/3/18, Роман <notifications@github.com> wrote:

 Subject: Re: [bondrogeen/web-server] Memory leak (#4)
 To: "bondrogeen/web-server" <web-server@noreply.github.com>
 Cc: "nedoskiv" <v_armenchev@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, March 3, 2018, 8:10 PM
 
 
 https://github.com/bondrogeen/web-server.RC522
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
