### ISSUE TITLE
Javascript fix

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#7]
I'm not a good in javascript programming, but while I edit your template start to learn a little.
Again can say "Thank you" about wonderful server and template. In the process I discovered a syntax error that usually gonna fire an error in other languages like Lua for example, in javascript it continue execution. Here is the part:

		send("web_control.lua", data, function (res) {
			if (res = "true") {
				send("web_control.lc", {
					init: "reboot"
				}, function (res) {

"if (res = "true")" should have two "=" instead on one. I usually do some mistake in lua, but compiler fire and error and correct me, here it works, actually always assume res = true.

**Comment by bondrogeen** [comment]
Thanks, fixed
