### ISSUE TITLE
some code not work on master branch

### ISSUE THREAD

**Issue by nedoskiv** [bondrogeen/web-server#9]
I have this code in an .html file (and few similar lines, all not working):
`<?lua local a=frj("listtitle") if a~=false then return ('<h2>Пълен списък на таговете с описание:</h2><a style="font-weight:bold;" href="fulllist.html">'..a.lt..'</a>') else return('<h2>Няма генериран списък</h2>')end?>`

on dev nodemcu release all works fine, but on master branch line is displayed "as is" from the browser. Web server do not catch it to execute as lua code. Short lines works, not sure where the problem is.

**Comment by bondrogeen** [comment]
<?lua local a=frj("listtitle") local r if a~= false then r='<h2>Пълен списък на таговете с описание:</h2><a style="font-weight:bold;" href="fulllist.html">'..a.lt..'</a>' else r='<h2>Няма генериран списък</h2>' end return r?>

and if so?

p.s. if the function returns a boolean, why not specify how
if a then ...  ?

**Comment by nedoskiv** [comment]
Code that you suggest do not work either, it is displayed as is into browser. Guess regexpr do not catch it somehow, but i'm not good with regexpr and cannot fix it :)

**Comment by bondrogeen** [comment]
Is there no new line in the code?
Can I look at the whole file?

**Comment by nedoskiv** [comment]
[rfidlist.html.gz](https://github.com/bondrogeen/web-server/files/1869237/rfidlist.html.gz)

**Comment by bondrogeen** [comment]
The file you have compressed it will not handle the embedded code. If you want the code to be processed, do not compress it in .gz
https://github.com/bondrogeen/web-server/blob/master/doc/en/README.md#restrictions

**Comment by nedoskiv** [comment]
I compress it because github do not allow me to upload .html file

**Comment by bondrogeen** [comment]
OK, I'll check later.

**Comment by bondrogeen** [comment]
I checked. The readline () problem in the documentation says that it reads 1024 bytes, but it turns out that 256 bytes

**Comment by bondrogeen** [comment]
Update the firmware of nodemcu, in the new version this problem was eliminated.

**Comment by bondrogeen** [comment]
Update the firmware, in the new version this problem was eliminated.

I just checked it.  
http://nodemcu-build.com/builds/nodemcu-master-19-modules-2018-04-04-15-06-33-integer.bin

**Comment by nedoskiv** [comment]
Thank you, I will stick to dev release.
